{ pkgs, cfg }:
let
  attrs = {
    "build-system" = {
      requires      = [ "uv_build>=0.9.0,<0.10.0" ];
      build-backend = "uv_build";
    };
    project = {
      name                  = cfg.name;
      version               = cfg.version;
      description           = cfg.description;
      readme                = cfg.readme;
      requires-python       = cfg.requiresPython;
      dependencies          = cfg.dependencies;
      scripts               = cfg.scripts;
      optional-dependencies = cfg.optionalDependencies;
    };
    "dependency-groups".dev   = cfg.devDependencies;
    "tool.pytest.ini_options" = {
      testpaths        = [ "tests" ];
      python_files     = [ "test_*.py" ];
      python_classes   = [ "Test*" ];
      python_functions = [ "test_*" ];
      addopts          = [ "-v" "--tb=short" "--strict-markers" "-p" "no:warnings" ];
      markers          = [
        "integration: requires real binaries (git, nix) installed"
        "slow: takes more than a few seconds"
      ];
    };
    "tool.coverage.run"    = { source = [ "tools" "config" "agent" ]; omit = [ "tests/*" "*/conftest.py" ]; };
    "tool.coverage.report" = { show_missing = true; skip_covered = false; };
    "tool.ruff"            = { line-length = 100; target-version = "py312"; };
    "tool.ruff.lint"       = { select = [ "E" "F" "I" "UP" ]; ignore = [ "E501" ]; };
  };

  jsonData = pkgs.writeText "pyproject-data.json" (builtins.toJSON attrs);

  writerPy = pkgs.writeText "write-pyproject.py" ''
    import json, sys

    with open(sys.argv[1]) as f:
        data = json.load(f)

    def to_toml_value(v):
        if isinstance(v, bool):    return "true" if v else "false"
        elif isinstance(v, int):   return str(v)
        elif isinstance(v, float): return str(v)
        elif isinstance(v, str):   return json.dumps(v)
        elif isinstance(v, list):
            if all(isinstance(i, (str, bool, int, float)) for i in v):
                return "[" + ", ".join(to_toml_value(i) for i in v) + "]"
            rows = ["["]
            for item in v: rows.append("    " + to_toml_value(item) + ",")
            rows.append("]")
            return "\n".join(rows)
        elif isinstance(v, dict):  return None
        return json.dumps(str(v))

    def write_section(out, key, value):
        if isinstance(value, dict):
            deferred = []
            out.append("\n[" + key + "]")
            for k, v in value.items():
                if isinstance(v, dict): deferred.append((k, v))
                else:
                    tv = to_toml_value(v)
                    if tv is not None: out.append(k + " = " + tv)
            for k, v in deferred:
                write_section(out, key + "." + k, v)
        else:
            tv = to_toml_value(value)
            if tv is not None: out.append(key + " = " + tv)

    lines = ["# Generated by flake.nix — edit in modules/project.nix"]
    for section, value in data.items():
        write_section(lines, section, value)

    with open(sys.argv[2], "w") as f:
        f.write("\n".join(lines) + "\n")
  '';

in { inherit jsonData writerPy; }